Angular FE
gsnovak/store pull request #6
Opened 2017-06-27 21:49 UTC by gsnovak

This is my start at an angular FE for my store.  @austinkahly @ksolkowski @mikeSheets

2017-06-28 14:21 UTC, mikeSheets requested changes

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +  Product.query().$promise.then (data) ->
Why does the checkout need to query Products?

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +    console.log "completing order"
console.log

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +    $scope.is_placed = ->
`$scope.is_placed = $scope.order.state is 'placed'`

Also move this up with the other cartPromise.then

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +      $scope.update_address()
$scope.update_address() if $scope.addr.id?

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +      $scope.update_cc()
One liner

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +      console.log("Adding to cart....")
Console.log

2017-06-28 14:21 UTC, mikeSheets commented on app/assets/javascripts/orders.coffee
> +  cartPromise.then (data) ->
Multiple `cartPromise.then`s

2017-06-28 14:21 UTC, mikeSheets commented on app/controllers/api/v1/base_controller.rb
> +    if @source_model.save
empty if

2017-06-28 14:21 UTC, mikeSheets commented on app/controllers/api/v1/base_controller.rb
> +    if @source_model.update(send("#{controller_name.singularize}_params"))
empty if

2017-06-28 14:21 UTC, mikeSheets commented on app/models/state.rb
> +
Double white space

2017-06-28 14:21 UTC, mikeSheets commented on app/views/orders/index.html.erb
> +<h1>Orders#index</h1>
should be able to kill the erbs, or convert them to haml

2017-06-28 14:21 UTC, mikeSheets commented on app/views/orders/show.html.erb
> +<h1>Orders#show</h1>
This too

2017-06-28 14:21 UTC, mikeSheets commented on app/views/products/index.html.haml
> +
WS

2017-06-28 14:21 UTC, mikeSheets commented on app/views/products/index.html.haml
> +            {{product.name}}
space inside the braces `{{ product.name }}`

2017-06-28 14:21 UTC, mikeSheets commented on app/views/products/index.html.haml
> +            {{product.price | currency : symbol : fractionSize}}
`{{ product.price | currency : symbol : fractionSize }}`

2017-06-28 20:04 UTC, fiestacasey requested changes

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      console.log("Adding to cart....")
^^

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +  cartPromise.then (data) ->
its weird to wait for the promise before defining the function, there's the risk that the button is clicked before the function exists which could cause unintended side affects if say a parent scope had a different function of the same name. You should do the cartPromise.then inside of the add to cart, so that the button can always be clicked but if the cartPromise is not complete it will wait for it before performing the action.

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.credit_card = new CreditCard(cc)
credit_card is underscore_case but you should use camelCase in javascript. there's a lot of that in here.

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.addr = new Address(add)
use address as a variable name, it providers greater clarity/readability

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.credit_card = new CreditCard(cc)
it will end up confusing as hell. `item_to_save.order_id` above should actually be `itemToSave.order_id`, but thats the way of the world....

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +  $scope.cc_init = (cc) ->
cc over creditCard I'm actually okay with as its an extremely common moniker.

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +    if $scope.addr.id?
out of curiosity, did you figure out checking the id if you should save or update on your own or..?

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +    if $scope.credit_card.id?
all of these saves need debouncing to avoid multiple server requests on a double click

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.order.$update()
order would always have an id right?

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.order.$update()
also, what is actually getting updated here? wouldn't you want to update the state to placed?

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +  $scope.update_order =  ->
this function doesn't appear to be used at all

2017-06-28 20:04 UTC, fiestacasey commented on app/controllers/api/v1/base_controller.rb
> +  def source_path
good functions 👍

2017-06-28 20:04 UTC, fiestacasey commented on app/controllers/api/v1/credit_cards_controller.rb
> +
remove unnecessary whitespace. with further denote this with a comment that just reads "WS"

2017-06-28 20:04 UTC, fiestacasey commented on app/models/address.rb
>    validates :zip_code, :state, presence: true
not sure how you can validate state if state isn't actually defined here? I think the belongs to was right... would use a unit test to confirm the relationship is setup correctly

2017-06-28 20:04 UTC, fiestacasey commented on app/models/order.rb
> +      puts "Quantity: #{item.inspect}, on hand count: #{item.source.on_hand_count}"
this looks like a debugging log, should remove debug statements before merging in with master / production code

2017-06-28 20:04 UTC, fiestacasey commented on app/views/checkout/index.html.haml
> +                  %select#exp-year.form-control.col-sm-2{"ng-model" => "credit_card.year"}
https://apidock.com/rails/ActionView/Helpers/DateHelper/select_year

2017-06-28 20:04 UTC, fiestacasey commented on app/views/checkout/index.html.haml
> +                  %select#exp-month.form-control.col-sm-2{"ng-model" => "credit_card.month"}
https://apidock.com/rails/ActionView/Helpers/DateHelper/select_month

2017-06-28 20:04 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.order.$save()
I don't fully get the workflow of the page... If I add my address, click save, then add my cc, click save, then click finish... it saves my address and CC again? 

maybe make the finish button just move the order to placed, but don't show it at all until after the address and cc are added? this then forces the user to click all 3 buttons

2017-06-28 20:04 UTC, fiestacasey commented on app/models/credit_card.rb
> +    self.last_four = number[-4..-1].to_i
this should be stored as text not an integer. What if my last four is 0077? then it would be saved as 77.

2017-06-28 20:04 UTC, fiestacasey commented on app/models/order.rb
> +      errors[:base] << "payment failed with #{payment.errors}"
payment.errors is a complex object that won't really translate to a string well

2017-06-28 20:04 UTC, fiestacasey commented on app/views/cart/address.html.erb
> +<h1>Cart#address</h1>
wuts dis

2017-06-28 20:04 UTC, fiestacasey commented on app/views/cart/billing.html.erb
> +<h1>Cart#billing</h1>
wuts dis

2017-06-28 20:04 UTC, fiestacasey commented on app/views/cart/index.html.erb
> +<h1>Cart#index</h1>
wuts dis

2017-06-28 20:04 UTC, fiestacasey commented on app/views/checkout/index.html.haml
> +              %input#first-address{"ng-model" => "addr.street_addr", type: "text", class: "form-control", placeholder: "Address"}
`ng: {model` bunch of that in here

2017-06-28 20:04 UTC, fiestacasey commented on app/views/checkout/index.html.haml
> +              %button.btn.btn-success{ng:{click:"update_address()"}}
pad `ng:{` with a space for readability `ng: {`

2017-06-28 20:04 UTC, fiestacasey commented on app/views/checkout/index.html.haml
> +              %button.btn.btn-success{ng:{click:"update_address()"}}
this is in other places too.

2017-06-28 20:04 UTC, fiestacasey commented on config/cloudinary.yml
> +  api_key: '884562686559465'
generally putting keys in a repo isn't good practice but this is really just a sample app so I think this is fine.

2017-06-28 20:06 UTC, fiestacasey commented
plz add some screenshots on how it looks/works

2017-06-29 14:32 UTC, gsnovak commented on app/assets/javascripts/orders.coffee
> +    if $scope.addr.id?
@fiestacasey I wasn't sure how else to check if it had already been created. Is there a better way to do this?

2017-06-29 15:05 UTC, ksolkowski commented on config/routes.rb
> +        get :cart
should specify if it's on a member or a collection. http://guides.rubyonrails.org/routing.html ```2.10.2 Adding Collection Routes```

2017-06-29 15:05 UTC, ksolkowski commented on db/schema.rb
> -    t.integer "state_id"
getting rid of state_id?

2017-06-29 15:05 UTC, ksolkowski commented on app/assets/javascripts/orders.coffee
> +      method: 'GET'
might have to set ```isArray: false```

2017-06-29 15:05 UTC, ksolkowski commented on app/controllers/api/v1/base_controller.rb
> +    @source_models = source_klass.all
shouldn't the show/index/create/update functions here be the ones to render json?

2017-06-29 15:05 UTC, ksolkowski commented on app/controllers/api/v1/products_controller.rb
> +    puts @products.to_json
puts

2017-06-29 15:05 UTC, ksolkowski commented on app/views/checkout/index.html.haml
> +              %button.btn.btn-success{ng:{click:"update_address()"}}
and similar thinking pad ```click:"function()"``` with a space ```click: "function()"```

2017-06-29 15:05 UTC, ksolkowski commented on app/views/products/index.html.haml
> +            {{product.price | currency : symbol : fractionSize}}
you can just ```{{ product.price | currency }}```

2017-06-29 22:01 UTC, gsnovak commented on app/controllers/api/v1/base_controller.rb
> +    @source_models = source_klass.all
Yes, but the CRUD operations should also be implemented here, right? I'll remove the actions I don't use.

2017-07-05 15:28 UTC, merged