Improvements
gsnovak/store pull request #7
Opened 2017-07-07 20:35 UTC by gsnovak

yo @fiestacasey @ksolkowski

2017-07-07 20:38 UTC, gsnovak commented
@fiestacasey @ksolkowski here's how it looks: https://dotpaper.herokuapp.com/

2017-07-07 20:39 UTC, fiestacasey requested changes

2017-07-07 20:39 UTC, fiestacasey commented on app/helpers/application_helper.rb
> -    # https://github.com/angular/angular.js/issues/1019 ng-init adds ng-selected option on select input
don't think you're actually using this. should be able to remove it

2017-07-07 20:39 UTC, fiestacasey commented on app/models/credit_card.rb
> -    self.last_four = number[-4..-1]
when assigning you do need to do `this.`, otherwise it just creates a local variable

2017-07-07 20:39 UTC, fiestacasey commented on app/models/order.rb
> +        errors[:base] << "There's not enough inventory to fullfill order!"
spelling fulfill

2017-07-07 20:39 UTC, fiestacasey commented on app/models/order.rb
> +  endssss
huh

2017-07-07 20:39 UTC, fiestacasey commented on app/models/order_item.rb
> +  validates :quantity, presence: true
source and order too?

2017-07-07 20:39 UTC, fiestacasey commented on config/environments/production.rb
> +  # config.assets.js_compressor = :uglifier
should be able to turn this back on since you updated your angular stuffs

2017-07-07 20:39 UTC, fiestacasey commented on test/models/order_test.rb
> +  test 'properly removes inventory' do
wut about payments? do they get processed correctly when an order is placed? and when an order is canceled?

2017-07-07 20:41 UTC, ksolkowski commented
not anywhere in this PR but if you go to https://dotpaper.herokuapp.com/checkout without being logged in..
![image](https://user-images.githubusercontent.com/2627962/27976106-c1307c2a-632a-11e7-8b97-81e8825e8edb.png)

2017-07-07 20:44 UTC, gsnovak commented on app/models/order.rb
> +  endssss
me command s-ing into oblivion

2017-07-07 20:47 UTC, ksolkowski requested changes

2017-07-07 20:47 UTC, ksolkowski commented on app/controllers/api/v1/base_controller.rb
> +    puts @source_model.errors.full_messages
puts!

2017-07-07 20:47 UTC, ksolkowski commented on app/controllers/api/v1/base_controller.rb
>      unless @source_model.update(send("#{controller_name.singularize}_params"))
what does it render if the update is successful?

2017-07-07 20:47 UTC, ksolkowski commented on app/controllers/api/v1/credit_cards_controller.rb
> +    params.require(:credit_card).permit(:first_name, :last_name, :number, :month, :year, :last_four, :user_id)
I don't think you need to have ```last_four``` in this list since it's being set in the model.

2017-07-07 20:47 UTC, ksolkowski commented on app/controllers/order_items_controller.rb
> +  def order_params
```order_item_params```

2017-07-07 20:47 UTC, ksolkowski commented on app/controllers/order_items_controller.rb
> +class  OrderItemsController < ApplicationController
double space after class

2017-07-07 20:47 UTC, ksolkowski commented on app/controllers/products_controller.rb
>  class  ProductsController < ApplicationController
double space.

2017-07-07 20:47 UTC, ksolkowski commented on app/models/order.rb
> -      item.source.on_hand_count -= item.quantity
this seems like it'd be the same as what you replaced it with

2017-07-07 20:47 UTC, ksolkowski commented on test/models/order_test.rb
> +    order.order_items << order_item
don't need to do that if you're specifying the order_id above

2017-07-07 20:47 UTC, ksolkowski commented on test/models/order_test.rb
> +    order_item = OrderItem.create(order_id: order.id, source_type: Product.name, source_id: product.id, quantity: 15)
if the order_item factory is set up should be able to do
```create(:order_item,order_id: order.id, source_type: Product.name, source_id: product.id, quantity: 15)```

2017-07-07 20:47 UTC, ksolkowski commented on test/models/order_test.rb
> +    order.user.credit_card = cc
should be able to do
```cc = create(:credit_card, user_id: order.user.id)``` 
then you won't have to do the order.user.credit_card = cc bit

2017-07-07 20:47 UTC, ksolkowski commented on test/models/order_test.rb
> +    order_item = OrderItem.create(order_id: order.id, source_type: Product.name, source_id: product.id, quantity: 15)
factory!

2017-07-07 20:47 UTC, ksolkowski commented on test/models/order_test.rb
> +    order.add_order_item << order_item
??

2017-07-07 20:54 UTC, gsnovak commented on app/controllers/api/v1/base_controller.rb
>      unless @source_model.update(send("#{controller_name.singularize}_params"))
what should i be rendering?

2017-07-07 20:56 UTC, ksolkowski commented on app/controllers/api/v1/base_controller.rb
>      unless @source_model.update(send("#{controller_name.singularize}_params"))
should be something like....
```ruby
def update
  if source model successfully updates
    render status: 200, json: @source_model
  else
    render status: 400, json: @source_model.errors.full_messages
  end
end
```

2017-07-07 21:02 UTC, gsnovak commented on test/models/order_test.rb
> +    order_item = OrderItem.create(order_id: order.id, source_type: Product.name, source_id: product.id, quantity: 15)
it would just be an empty factory since all the fields are getting set here, right?

2017-07-10 16:52 UTC, gsnovak commented
@fiestacasey fixed AR issues

2017-07-11 15:32 UTC, gsnovak commented
@fiestacasey is this okay to merge?

2017-07-11 20:17 UTC, fiestacasey reviewed
looking good here

2017-07-11 20:17 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +app.controller 'ProductsController', ['$scope', 'Product', 'OrderItem', 'Order', '$window', ($scope, Product, OrderItem, Order, $window) ->
@murphyjoseph I would bet we'll need to do this with the redesign too. Different uglifiers...

2017-07-11 20:17 UTC, fiestacasey commented on app/assets/javascripts/orders.coffee
> +      $scope.orderErrors = result.data.orders
i don't recognize the syntax for these. I would expect you tested and are doing it right but there's also some inconsistency on the pluralization of this. address vs credit_cards, etc.

2017-07-11 20:17 UTC, fiestacasey commented on app/models/state_change.rb
> +  belongs_to :source, polymorphic: true, optional: true
is this still needed?

2017-07-11 20:34 UTC, gsnovak commented on app/assets/javascripts/orders.coffee
> +      $scope.orderErrors = result.data.orders
I think it's tied to the controller ( i.e. credit_cards_controller.rb, address_controller.rb, etc... ). I'll change the naming to be more consistent.

2017-07-11 20:35 UTC, gsnovak commented on app/models/state_change.rb
> +  belongs_to :source, polymorphic: true, optional: true
No, I'll remove it.

2017-07-11 20:53 UTC, merged