changed permissions to use cancancan gem
gsnovak/store pull request #9
Opened 2017-07-13 21:12 UTC by gsnovak

cancancancancancancancancancancan gem

2017-07-13 21:19 UTC, gsnovak commented on app/models/credit_card.rb
> +  #this needs to be fixed before_save :set_last_four
just pretend this works for now

2017-07-14 13:30 UTC, fiestacasey requested changes

2017-07-14 13:30 UTC, fiestacasey commented on app/controllers/api/v1/base_controller.rb
>    before_action :retrieve_source_model_by_id, only: [:edit, :update, :destroy, :show]
I don't think you need this now that you are using cancancan. You should be able to refer to the model as `resource`

2017-07-14 13:30 UTC, fiestacasey commented on app/models/ability.rb
> +      user ||= User.new
how many spaces are you using?!?!?!?!!?

2017-07-14 16:21 UTC, fiestacasey commented on app/models/credit_card.rb
> +    self.last_four = number[-4..-1] if not number.nil?
```unless number.nil?```

2017-07-14 19:22 UTC, merged